core/users/routes.py
import json
from pathlib import Path
from flask import Blueprint, render_template, redirect, url_for, flash, request, abort
from .forms import (
    RegistrationForm,
    GalleryForm,
    LoginForm,
    ProgramForm,
    SubProgramForm,
    CommunityForm,
    HousingForm,
    SportArtForm,
    YouthEmpowerMentForm,
    BlogForm,
    TestimonialForm,
    OurTeamForm
)
from flask_login import current_user, login_user, login_required, logout_user
from core.models import (
    User, 
    db, 
    Blog, 
    Program,
    SubProgram,
    Testimonial, 
    OurTeam,
    Gallery,
    Community,
    Housing,
    SportsArt,
    YouthEmpowerMent)
from core.extensions import bcrypt
from .utils import create_path



users = Blueprint("users", __name__)

# admin section

PATH = Path().absolute()





@users.route("/admin/register", methods=["GET", "POST"])
def register():
    if current_user.is_authenticated:
        return redirect(url_for("users.home"))
    form = RegistrationForm()
    if form.validate_on_submit():
        if User.query.count() < 1:

            hash_password = bcrypt.generate_password_hash(form.password.data).decode(
                "utf-8"
            )
            admin = User(username=form.username.data, password=hash_password)
            db.session.add(admin)
            db.session.commit()
            flash(
                "Your account has been created! You are now able to log in", "success"
            )
            return redirect(url_for("users.program"))
    return render_template("register.html", form=form)


@users.route("/admin/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for("users.create_program"))
    form = LoginForm()
    if form.validate_on_submit():
        admin = User.query.filter_by(username=form.username.data).first()
        if admin and bcrypt.check_password_hash(admin.password, form.password.data):
            login_user(admin)
            next_page = request.args.get("next")
            return redirect(next_page) if next_page else redirect(url_for("users.home"))
        else:
            flash("Login Unsuccessfull. Please check username and password", "danger")
    return render_template("login.html", title="login", form=form)


@users.route("/admin/create_program", methods=["GET", "POST"])
@login_required
def create_program():
    form = ProgramForm()
    if form.validate_on_submit():
        program = Program(
            title=form.title.data,
            user_id=current_user.id)
        db.session.add(program)
        db.session.commit()
        return redirect(url_for('users.program'))
    return render_template("create_program.html",form=form)


@users.route("/admin/program/<int:program_id>/delete", methods=["POST"])
@login_required
def delete_program(program_id):
    program = Program.query.get_or_404(program_id)
    if program.user != current_user:
        abort(403)
    db.session.delete(program)
    db.session.commit()
    return redirect(url_for("users.program"))



@users.route('/program/<int:program_id>/create_subprogram', methods=['GET', 'POST'])
@login_required
def create_subprogram(program_id):
    # 1. Ensure the parent Program exists
    program = Program.query.get_or_404(program_id)
    form = SubProgramForm()
    if request.method == "POST":
        file = request.files['subprogram_image']
        if file:
            image_path = create_path("sub_program", file)
            subprogram = SubProgram(
                title = form.title.data,
                content=form.content.data,
                image_file=image_path,
                program_id=program.id,
                user_id=current_user.id
            )
            db.session.add(subprogram)
            db.session.commit()
            return redirect(url_for("users.program_detail" , program_id=program.id))
    return render_template("create_subprogram.html", form=form, program=program)

@users.route("/admin/subprogram/<int:sub_program_id>/delete", methods=["POST"])
@login_required
def delete_subprogram(sub_program_id):
    sub_program = SubProgram.query.get_or_404(sub_program_id)
    program_id = sub_program.program_id
    if sub_program.user != current_user:
        abort(403)
    db.session.delete(sub_program)
    db.session.commit()
    return redirect(url_for("users.program_detail",program_id=program_id))

@users.route("/admin/community_program", methods=["GET", "POST"])
@login_required
def create_community_program():
    form = CommunityForm()
    if request.method == "POST":
        file = request.files["subprogram_image"]
        if file:
            image_path = create_path("community",file)
            program = Community(
                    title = form.title.data,
                    content=form.content.data,
                    image_file=image_path,
                      user_id=current_user.id,
            )
            db.session.add(program)
            db.session.commit()
            return redirect(url_for("users.community_program"))

    return render_template("create_community.html", form=form)



@users.route("/admin/program_intro", methods=["GET", "POST"])
@login_required
def create_program_intro():
    form = YouthEmpowerMentForm()
    if request.method == "POST":
        file = request.files["subprogram_image"]
        if file:
            image_path = create_path("youth",file)
            
            my_dict = {
                "title" : form.title.data,
                "content": form.content.data,
                "image_file": image_path
            }
            with open('program_intro.json', 'w') as file:
                json.dump(my_dict, file)
           
            return redirect(url_for("users.home"))

    return render_template("create_youth.html", form=form)


@users.route("/admin/delete_program_intro", methods=["GET", "POST"])
@login_required
def delete_program_intro():
    my_dict = {}
    with open(PATH / "program_intro.json" , "w") as f:
        json.dump(my_dict, f)
    
           
    return redirect(url_for("users.home"))


@users.route("/admin/create_title_intro", methods=["GET", "POST"])
@login_required
def create_title_intro():
    form = YouthEmpowerMentForm()
    if request.method == "POST":
        file = request.files["subprogram_image"]
        if file:
            image_path = create_path("youth",file)
            my_dict = {
                "title" : form.title.data,
                "content": form.content.data,
                "image_file": image_path
            }
            with open('title_intro.json', 'w') as file:
                json.dump(my_dict, file)
           
            return redirect(url_for("users.home"))

    return render_template("create_title.html", form=form)


@users.route("/admin/delete_title_intro", methods=["GET", "POST"])
@login_required
def delete_title_intro():
    my_dict = {}
    with open(PATH / "title_intro.json" , "w") as f:
        json.dump(my_dict, f)
    
           
    return redirect(url_for("users.home"))
    



@users.route("/admin/housing_program", methods=["GET", "POST"])
@login_required
def create_housing_program():
    form = HousingForm()
    if request.method == "POST":
        file = request.files["subprogram_image"]
        if file:
            image_path = create_path("housing",file)
            program = YouthEmpowerMent(
                    title = form.title.data,
                    content=form.content.data,
                    image_file=image_path,
                    user_id=current_user.id,
                    
                    
            )
            db.session.add(program)
            db.session.commit()
            return redirect(url_for("users.housing_program"))

    return render_template("create_housing.html", form=form)

@users.route("/admin/sports_program", methods=["GET", "POST"])
@login_required
def create_sports_program():
    form = SportArtForm()
    if request.method == "POST":
        file = request.files["subprogram_image"]
        if file:
            image_path = create_path("sports",file)
            program = YouthEmpowerMent(
                    title = form.title.data,
                    content=form.content.data,
                    image_file=image_path,
                     user_id=current_user.id,
            )
            db.session.add(program)
            db.session.commit()
            return redirect(url_for("users.sports_program"))

    return render_template("create_sports.html", form=form)



@users.route("/admin/blog", methods=["GET", "POST"])
@login_required
def create_blog():
    form = BlogForm()
    if request.method == "POST":
        file = request.files["blog_image"]
        if file:
            image_path = create_path("blog", file)
            blog = Blog(
                title=form.title.data,
                content=form.content.data,
                image_file=image_path,
                user_id=current_user.id,
            )
            db.session.add(blog)
            db.session.commit()
            return redirect(url_for("users.blog"))
    return render_template("create_blog.html", form=form)


@users.route("/admin/blog/<int:blog_id>/delete", methods=["POST"])
@login_required
def delete_blog(blog_id):
    blog = Blog.query.get_or_404(blog_id)
    if blog.user != current_user:
        abort(403)
    db.session.delete(blog)
    db.session.commit()
    return redirect(url_for("users.blog"))


@users.route("/admin/testimonial", methods=["GET", "POST"])
@login_required
def create_testimonial():
    form = TestimonialForm()
    if request.method == "POST":
        file = request.files["profile_image"]
        if file:
            image_path = create_path("testimonial", file)
            testimony = Testimonial(
                name=form.name.data,
                content=form.content.data,
                profile_pic=image_path,
                user_id=current_user.id,
            )
            db.session.add(testimony)
            db.session.commit()

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
      <!-- web icon -->
    <link rel="shortcut icon" href="{{ url_for('static', filename='images/icon.jpg') }}">


    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Inua Collective Society</title>
   
    <script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>
    <script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
    <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet"> 
    <script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/feather-icons/dist/feather.min.js"></script>
    <script src="https://unpkg.com/feather-icons"></script>
    <script src="https://cdn.jsdelivr.net/npm/vanta@latest/dist/vanta.globe.min.js"></script>
  
    <!-- Preline js -->
    <script src="https://unpkg.com/preline/dist/preline.js"></script>


        <!--=============== REMIXICONS ===============-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/remixicon/4.2.0/remixicon.min.css">
   


    <!-- Link for Swipper -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css" />

    <!-- Link For awesome fonts -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css"
        integrity="sha512-Evv84Mr4kqVGRNSgIGL/F/aIDqQb7xQ2vcrdIwxfjThSH8CSR7PBEakCr51Ck+w+/U6swU2Im1vVX0SVk9ABhg=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />

  
    <link rel="stylesheet" href="{{url_for('static',filename='dist/output.css')}}">
    
    <!-- Google Icons -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200&icon_names=arrow_drop_down&display=block" />

  
    <style>
      .hero-bg {
            background: linear-gradient(45deg,  #eb764f 3%,#7fb5e0 23%);
        }
        .donate-btn {
            transition: all 0.3s ease;
        }
        .donate-btn:hover {
            transform: translateY(-3px);
            box-shadow: 0 10px 20px rgba(0, 0, 0, 0.1);
        }
        .inset_shandow {
            box-shadow: inset 0 3px 10px rgba(0, 0, 0, 0.1);
        }
        .box_shadow {
            box-shadow: 2px 2px 2px 1px rgb(0 0 0 / 20%)
        }
    </style>
</head>
<body class="font-[Poppins] anitialised text-gray-800">
    {% include "navbar.html" %}
    
    {% block content %}
    {% endblock %}
     <!-- Footer -->
    <footer class="bg-gray-800 text-white py-12">
        <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
            <div class="md:flex md:justify-between md:items-center">
                <div class="mb-8 md:mb-0">
                    <div class="flex items-center">
                        <!-- <i data-feather="heart" class="text-red-500 mr-2"></i> -->
                         <img src="{{ url_for('static', filename='images/logo.png') }}" alt="inua logo" class="rounded-lg w-8 h-8  mr-2">
                        <span class="text-xl font-bold">Inua Collective Society</span>
                    </div>
                    <p class="mt-4 text-gray-400 max-w-md">Empowering communities through sustainable development programs in education and economic empowerment.</p>
                </div>
                <div class="grid grid-cols-2 md:grid-cols-3 gap-8">
                    <div>
                        <h3 class="text-sm font-semibold text-gray-300 tracking-wider uppercase mb-4">Quick Links</h3>
                        <ul class="space-y-2">
                            <li><a href="#home" class="text-gray-400 hover:text-white">Home</a></li>
                            <li><a href="#about" class="text-gray-400 hover:text-white">About</a></li>
                            <li><a href="#Program" class="text-gray-400 hover:text-white">Programs</a></li>
                            <li><a href="#impact" class="text-gray-400 hover:text-white">Blog</a></li>
                            <li><a href="#contact" class="text-gray-400 hover:text-white">Event</a></li>
                            <li><a href="#contact" class="text-gray-400 hover:text-white">Gallery</a></li>
                        </ul>
                    </div>
                    <div>
                        <h3 class="text-sm font-semibold text-gray-300 tracking-wider uppercase mb-4">Legal</h3>
                        <ul class="space-y-2">
                            <li><a href="#" class="text-gray-400 hover:text-white">Privacy Policy</a></li>
                            <li><a href="#" class="text-gray-400 hover:text-white">Terms of Service</a></li>
                            <li><a href="#" class="text-gray-400 hover:text-white">Financial Reports</a></li>
                        </ul>
                    </div>
                    <div>
                        <h3 class="text-sm font-semibold text-gray-300 tracking-wider uppercase mb-4">Subscribe</h3>
                        <p class="text-gray-400 mb-4">Stay updated with our latest news and stories.</p>
                        <form class="flex">
                            <input type="email" placeholder="Your email" class="px-4 py-2 rounded-l-md focus:outline-none text-gray-800 w-full">
                            <button type="submit" class="bg-blue-600 hover:bg-blue-700 px-4 py-2 rounded-r-md">
                                <i data-feather="send" class="w-4 h-4"></i>
                            </button>
                        </form>
                    </div>
                </div>
            </div>
            <div class="mt-12 pt-8 border-t border-gray-700 text-center text-gray-400 text-sm">
                <p>© 2025 Inua Collective <a href="{{ url_for("users.login")}}">Soc</a>iety. All rights reserved</p>
            </div>
        </div>
    </footer>

     <!-- script Swipper Link -->

    <script src="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.js"></script>
   
    <!-- Main Script Link -->
    <script src="{{ url_for('static', filename='js/script.js') }}"></script>
      

</body>
</html>

templates/community.html
{% extends 'base.html' %}

{% block content %}

  <section id="home"  class="text-white pt-32 pb-20 bg-gray-100" id="vanta-globe">
        <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
             <div class="text-center mb-16" data-aos="fade-up">
                <h2 class="text-3xl font-bold text-gray-800 mb-4">Community Empowerment,
Advocacy &amp; Development.</h2>
                <div class="w-80 h-1 bg-blue-600 mx-auto"></div>
            </div>
            {% if current_user.is_authenticated %}
                <div class="absolute rounded-xl bg-blue-200 pb-3 pt-3 pl-2 pr-2 right-[2%]" data-aos="fade-left">
                    <a href="{{ url_for('users.create_community_program')}}">create program</a>
                    <ion-icon name="add" class=""></ion-icon>
                </div>
            {% endif %}
            <div class="flex flex-col md:flex-row md:items-center md:justify-between gap-y-6 md:gap-x-6 mt-[150px]">
                 {% for program in programs %}
                <div class="max-w-[420px] rounded-[10px] overflow-hidden group">
                    <div class="relative overflow-hidden" data-aos="fade-left">
                        <img src="{{ url_for('static', filename=program.image_file)}}" class="group-hover:scale-110 transition-all w-full duration=500">

                        <div class="bg-blue-100 absolute bottom-0 left-0 text-gray-800 text-base tracking-[2.24px]
                        uppercase py-[6px] px-[18px]">{{ program.title }}</div>
                    </div>
                    <div class="px-5 py-6" data-aos="fade-right">
    
                        <p class="font-light text-gray-700">{{ program.content|truncatewords(20) }}
                            <a class="italic underline text-[#4c5354] hover:bg-white hover:text-blue-600 transition">
                                Read More
                            </a>
                        
                        </p>
                       
                        
                    </div>
                    {% if current_user.is_authenticated %}
                        <form class="absolute top-[1%] right-[1%]" action="" method="POST"> 
                            <button type="submit" class="fa-solid fa-trash text-[1.5rem] text-red-600"></button> 
                        </form> 
                    {% endif %} 
                </div>
               
                {% endfor %}
             
            </div>
        </div>
    </section>
   


{% endblock %}

templates/create_program.html
{% extends 'base.html' %}

{% block content %}

  <section id="home"  class="text-white pt-32 pb-20 bg-sky-100" id="vanta-globe">
        <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
             <div class="text-center mb-16" data-aos="fade-up">
                <h2 class="text-3xl font-bold text-gray-800 mb-4">Create Program</h2>
                <div class="w-30 h-1 bg-blue-600 mx-auto"></div>
            </div>
            
            <div class="flex justify-center item-center"  data-aos="fade-down">
               
                  <form method="post" enctype="multipart/form-data" action="">
                        {{ form.hidden_tag() }}
                        <div class="flex flex-col bg-sky-50 shadow-md px-10 py-4 rounded-lg gap-3">
                            

                            <div class="py-4 my-1">
                                {{ form.title(class='border-b-slate-900 px-2 py-2 w-full text-gray-800 shadow', placeholder='Sub Program Title') }}
                               
                            </div>
                          
                           
                          
                            <div class="py-4">
                                {{ form.submit(class='text-center bg-green-200 w-full  rounded-lg text-gray-800 my-3 py-2') }}
                            </div>
                        </div>
                    </form>


                
            </div>
             
          
        </div>
    </section>

{% endblock %}

templates/home.html
{% extends 'base.html' %}

{% block content %}

    <section id="home" class="hero-bg relative text-white pt-32 pb-20" id="vanta-globe">
        <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
            {% if current_user.is_authenticated %}
            <div class="absolute rounded-lg bg-blue-500 pb-3 pt-3 pl-4 pr-4 left-[0%] hover:bg-[oldlace] hover:border-1 hover:text-gray-800" data-aos="fade-left">
                <a class="" href="{{ url_for('users.create_title_intro')}}">create title intro</a>
                <ion-icon name="add" class=""></ion-icon>
            </div>
        
            <form class="absolute right-[1%]" action="{{ url_for('users.delete_title_intro')}}" method="POST"> 
                <button type="submit" class="fa-solid fa-trash text-[1.5rem] text-red-600"></button> 
            </form> 
               
            {% endif %}
            <div class="flex flex-col md:flex-row md:items-center md:justify-between items-center gap-2 mt-8">
                <div class="md:w-1/2" data-aos="fade-right">
                    <h1 class="text-2xl md:text-5xl font-bold leading-tight mb-6">{{ info.title }}</h1>
                    <p class="text-sm mb-8">{{ info.content }}</p>
                    <div class="flex space-x-4 items-center">
                        
                        <a href="{{ url_for('users.about')}}" class="border-2 border-white text-white px-8 py-3 rounded-full font-bold hover:bg-white hover:text-blue-600 transition">
                            Learn More
                        </a>
                    </div>
                </div>
                <div class="md:block md:w-1/2" data-aos="fade-left ">
                     <img src="{{ url_for('static', filename=info.image_file)}}" class="rounded-lg shadow-2xl object-cover w-full h-auto">
                </div>
            </div>
        </div>
    </section>

    <!-- <section id="home"  class="text-white pt-32 pb-20 bg-gray-100" id="vanta-globe">
        <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
             <div class="text-center mb-16" data-aos="fade-up">
                <h2 class="text-3xl font-bold text-gray-800 mb-4">What We Do</h2>
                <div class="w-20 h-1 bg-blue-600 mx-auto"></div>
            </div>
            {% if current_user.is_authenticated %}
            <div class="absolute rounded-lg bg-blue-500 pb-3 pt-3 pl-4 pr-4 right-[5%] hover:bg-[oldlace] hover:border-1 hover:text-gray-800" data-aos="fade-left">
                <a class="" href="{{ url_for('users.create_program_intro')}}">create program intro</a>
                <ion-icon name="add" class=""></ion-icon>
            </div>
        
            <form class="absolute right-[2%]" action="{{ url_for('users.delete_program_intro')}}" method="POST"> 
                <button type="submit" class="fa-solid fa-trash text-[1.5rem] text-red-600"></button> 
            </form> 
               
            {% endif %}

             
            <div class="md:flex md:items-center md:justify-between gap-8">
                <div class="md:block md:w-1/2 items-center" data-aos="fade-left">
                     <img src="{{ url_for('static', filename=program.image_file)}}" class="rounded-lg shadow-2xl ml-2">
                </div>
                  <div class="md:w-1/2" data-aos="fade-right">
                    <h1 class="text-gray-800 text-2xl md:text-2xl font-bold leading-tight mb-6">  {{ program.title }}</h1>
                    <p class="text-lg text-gray-800 mb-8 line-clamp-4">{{ program.content }}</p>
                    <div class="flex space-x-4">
                        
                        <a href="{{ url_for('users.program')}}" class="border-2 border-cyan-500 text-gray-800 px-8 py-3 rounded-full font-bold hover:bg-white hover:text-blue-600 transition">
                            More Programs
                        </a>
                    </div>
                </div>
                
            </div>
        </div>
    </section> -->
   

    <!-- Testimonial -->
    <section id="causes" class="py-20 bg-white">
        <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
            <div class="text-center mb-16" data-aos="fade-up">
                <h2 class="text-3xl font-bold text-gray-800 mb-4">Voices of Impact</h2>
                <div class="w-20 h-1 bg-blue-600 mx-auto"></div> 
            </div>
             {% if current_user.is_authenticated %}
            <div class="absolute rounded-lg bg-blue-500 pb-3 pt-3 pl-4 pr-4 right-[2%] hover:bg-[oldlace]" data-aos="fade-left">
                <a class="" href="{{ url_for('users.create_testimonial')}}">create Testimonial</a>
                <ion-icon name="add" class=""></ion-icon>
            </div>
            {% endif %}
            <div class="slide-container swiper mt-[150px]"> 
                <div class="slider-wrapper">
                     <ul class="swiper-wrapper"> 
                        {% for testimonial in testimonials %} 
                            <div class="select-none flex flex-col item-center p-[35px] relative text-center swiper-slide" data-aos="zoom-in"> 
                                <img class="w-[180px] h-[180px] object-cover rounded-full mb-[50px] mx-auto" src="{{ url_for('static', filename=testimonial.profile_pic)}}" alt=""> 
                                <h3 class="mb-4 text-[1.12rem]">{{ testimonial.name }}</h3> 
                                <p class="leading-[25px]">{{ testimonial.content }}</p> 
                                {% if current_user.is_authenticated %}
                                    <form class="absolute top-[2%] right-[30%]" action="{{ url_for('users.delete_testimony', testimony_id=testimonial.id)}}" method="POST"> 
                                        <button type="submit" class="fa-solid fa-trash text-[1.5rem] text-red-600"></button> 
                                    </form> 
                                {% endif %} 
                            </div> {% endfor %} 
                    </ul> 
                    <div class="swiper-pagination"></div> 
                    <div class="swiper-button-prev text-[#e6b762] mt-[50px] transition duration-300 ease-in-out hover:text-[oldlace]"></div> 
                    <div class="swiper-button-next text-[#e6b762] mt-[50px] transition duration-300 ease-in-out hover:text-[oldlace]"></div> 
                </div>


        </div>
    </section>
    

{% endblock %}

templates/program.html
{% extends 'base.html' %}

{% block content %}

  <section id="home"  class="text-white pt-32 pb-20 bg-gray-100" id="vanta-globe">
        <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
             <div class="text-center mb-16" data-aos="fade-up">
                <h2 class="text-3xl font-bold text-gray-800 mb-4">Programs</h2>
                <div class="w-20 h-1 bg-blue-600 mx-auto"></div>
            </div>
            {% if current_user.is_authenticated %}
                <div class="absolute rounded-lg bg-blue-500 pb-3 pt-3 pl-4 pr-4 right-[2%]" data-aos="fade-left">
                    <a href="{{ url_for('users.create_program')}}">create program</a>
                    <ion-icon name="add" class=""></ion-icon>
                </div>
            {% endif %}
            <div class="flex flex-col md:flex-col md:items-center md:justify-between gap-y-6 md:gap-x-6 mt-[150px]">
                 {% for program in programs %}
                <a href="{{ url_for('users.program_detail', program_id=program.id) }}" class="max-w-[600px] relative bg-blue-200 py-8 px-8 rounded-[10px] relative overflow-hidden group hover:-translate-2 hover:bg-transparent hover:border-gray-800 hover:border-2">
                    <div class="overflow-hidden" data-aos="fade-left">
    

                        <div class="bottom-0 left-0 text-gray-800 py-12 px-8 text-base tracking-[2.24px]
                        uppercase py-[6px] px-[18px]">{{ program.title }}</div>
                    </div>
                 
                     {% if current_user.is_authenticated %}
                        <form class="absolute top-[10%] right-[10%]" action="{{ url_for('users.delete_program', program_id=program.id) }}" method="POST"> 
                            <button type="submit" class="fa-solid fa-trash text-[1.5rem] text-red-600"></button> 
                        </form> 
                    {% endif %} 
                </a>
               
                {% endfor %}
             
            </div>
        </div>
    </section>
   


{% endblock %}

templates/program_detail.html
{% extends 'base.html' %}

{% block content %}

  <section id="home"  class="text-white pt-32 pb-20 bg-gray-100" id="vanta-globe">
        <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
             <div class="text-center mb-16" data-aos="fade-up">
                <h2 class="text-3xl font-bold text-gray-800 mb-4">{{ program.title }}</h2>
                <div class="w-80 h-1 bg-blue-600 mx-auto"></div>
            </div>
            {% if current_user.is_authenticated %}
                <div class="absolute rounded-xl bg-blue-600 pb-3 pt-3 pl-6 pr-6 right-[2%]" data-aos="fade-left">
                    <a href="{{ url_for('users.create_subprogram' , program_id=program.id)}}">create sub program</a>
                    <ion-icon name="add" class=""></ion-icon>
                </div>
            {% endif %}
            <div class="flex flex-col md:flex-row md:items-center md:justify-between gap-y-6 md:gap-x-6 mt-[150px]">
                 {% for prog in program.subprograms %}
                <div class="max-w-[420px] relative rounded-[10px] overflow-hidden group">
                    <div class="relative overflow-hidden" data-aos="fade-left">
                        <img src="{{ url_for('static', filename=prog.image_file)}}" class="hover:scale-110 transition-all duration=500">

                        <div class="bg-blue-100 absolute bottom-0 left-0 text-gray-800 text-base tracking-[2.24px]
                        uppercase py-[6px] px-[18px]">{{ prog.title }}</div>
                    </div>
                    <div class="px-5 py-6" data-aos="fade-right">
    
                        <p class="font-light text-gray-700 line-clamp-3">{{ prog.content }}
                          
                        
                        </p>
                        <a href="{{ url_for('users.sub_program_detail', sub_program_id=prog.id)}}" class="italic underline text-lg text-[#4c5354] hover:bg-white hover:text-blue-600 transition">
                                Read More
                        </a>
                       
                        
                    </div>
                    {% if current_user.is_authenticated %}
                        <form class="absolute top-[1%] right-[1%]" action="{{ url_for('users.delete_subprogram', sub_program_id=prog.id)}}" method="POST"> 
                            <button type="submit" class="fa-solid fa-trash text-[1.5rem] text-red-600"></button> 
                        </form> 
                    {% endif %} 
                </div>
               
                {% endfor %}
             
            </div>
        </div>
    </section>
   


{% endblock %}